#include "web_site/style.h"
#include "web_site/javascript.h"

char html[] =
"<!DOCTYPE html>\n"
"<html lang=\"pt-br\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<title>Estação Meteorológica</title>\n"
"\n <style>" STYLE_PAGE
    "</style>"
"<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
"</head>\n"
"<body>\n"
"<h1>Estacao Metereologica</h1>\n"
"<div id=\"info\">\n"
"<h3>Temperatura:<span>°C</span></h3>\n"
"<h3>Umidade:<span>%</span></h3>\n"
"<h3>Pressão:<span>kpa</span></h3>\n"
"</div>\n"
"<div id=\"container\">\n"
"<div><select id=\"varSelect\">\n"
"<option value=\"temp\">Temperatura</option>\n"
"<option value=\"umi\">Umidade</option>\n"
"<option value=\"pres\">Pressão</option>\n"
"</select></div>\n"
"<div id=\"div_inp_minMax\">\n"
"<div class=\"form-linha\"><label for=\"min\">Minimo:</label><input type=\"number\" min=\"0\" placeholder=\"Min\" value=\"0\"></div>\n"
"<div class=\"form-linha\"><label for=\"max\">Maximo:</label><input type=\"number\" min=\"0\" placeholder=\"Max\" value=\"0\"></div>\n"
"<div class=\"form-linha\"><label for=\"ajuste\">Ajuste:</label><input type=\"number\" min=\"0\" placeholder=\"Calibragem\" value=\"0\"></div>\n"
"<button>Enviar</button>\n"
"</div>\n"
"</div>\n"
"<h3>Variacao em Tempo Real</h3>\n"
"<canvas id=\"grafico\"></canvas>\n"
"<script>" JAVA_SCRIPT "</script>\n"
"</body>\n"
"</html>\n";
